version: "3.9"

services:
  web:
    build: ./services/web
    command: python -m flask run --host=0.0.0.0
    volumes:
      - ./services/web/:/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine3.15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=super
      - POSTGRES_DB=my_database


volumes:
  postgres_data: